name: clean_digital_web
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.3
  flutter_form_builder: ^7.0.0
  form_builder_validators: ^7.2.0
  logger: ^1.1.0
  flutter_svg: ^0.23.0+1
  retrofit: ^2.2.0
  equatable: ^2.0.3
  json_annotation: ^4.3.0
  json_serializable: ^6.0.0
  injectable: ^1.5.0
  get_it: ^7.2.0
  flutter_bloc: ^7.3.1
  flutter_multi_formatter: ^2.4.1
  infinite_scroll_pagination: ^3.1.0
  jwt_decode: ^0.3.1
  auto_size_text: ^3.0.0
  flutter_spinkit: ^5.1.0
  auto_route: ^3.2.4
  fluttericon: ^2.0.0
  shared_preferences: ^2.0.15
  responsive_framework: ^0.1.8
  flex_color_scheme: ^5.0.1
  google_fonts: ^2.3.2
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^2.1.0+1
  build_runner: ^2.1.4
  injectable_generator: ^1.5.2
  auto_route_generator: ^3.2.3

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
